### PR TITLE
Added changePrefix for multi-app usage.

### PR DESCRIPTION
**Pull request by ChicagoDave**
In an enterprise environment, local storage may be used as a dependency
for multiple applications. Forcing the prefix to be set by the
encapsulating enterprise framework prevents developers from overwriting
each others local storage.

### CODE REVIEW

**Comment by thoughtpalette** [comment]
+1

**Comment by ChicagoDave** [comment]
A note on this...I didn't quite get the unit test right, so I'm working on that. The code works, but I want to make sure it's tested properly.

**Comment by a8m** [comment]
@ChicagoDave can you squash these commits?
thanks

**Comment by ChicagoDave** [comment]
Squished.

**Comment by episodeyang** [comment]
This is very badly needed! I don't personally care about the name of the method, but I do think it makes more sense to call it `setPrefix`, instead of changePrefix.

**Comment by grevory** [comment]
Thanks for your patience. Try it now.

**Pull request merged**
