### PR TITLE
angular-local-storage reborn

### PR DESCRIPTION
**Pull request by ealves-pt**

### CODE REVIEW

**Comment by ealves-pt** [comment]
@g2graman, @grevory

Need two thumbs up for this PR.

I'm sure I have managed to keep backwards compatibility but I want some feedback before merging this.

**Comment by grevory** [comment]
I ran the test and I am getting the error "Unable to inialize angular-local-storage" on /dist/angular-local-storage.js:17

Also, notice the typo in "inialize."

**Comment by ealves-pt** [comment]
@grevory I have fixed the typo. But the error you mentioned is weird. Did you run `bower install` before running the tests?

**Comment by grevory** [comment]
:facepalm:

I ran `npm install`. Looks good.

**Comment by ealves-pt** [comment]
Nice. I will merge this and keep looking at the open PR. :+1:

**Pull request merged**
