### PR TITLE
Set individual expiry for cookies

### PR DESCRIPTION
**Pull request by RijulB**
Allow cookies to have individual expiry.

### CODE REVIEW

**Comment by RijulB** [comment]
Issues #200 #145

**Comment by a8m** [comment]
Looks good @RijulB! I'll take a look later.
Thx.

**Comment by a8m** [comment]
@RijulB can you update the docs please? 
I'll merge it and bump version.
thx

**Comment by RijulB** [comment]
@a8m Done and Pushed. Thanks.

**Comment by a8m** [comment]
Great.
Thanks @RijulB

**Pull request merged**
