### PR TITLE
add setStorageType from localStorageService

### PR DESCRIPTION
**Pull request by william57m**
A lot of users and me need to change storage type according to application behaviors, so I add setStorageType method directly callable from localStorageService. Maybe there are better solution (for example, give a storageType parameter directly in set method...), but I think this can help people.

### CODE REVIEW

**Comment by ealves-pt** [comment]
@william57m I know it has been a full more that 1yr since you have created this PR. Can I ask you to rebase with the master and try to fix the conflicts? I would really like to merge this functionality.

If you don't want to waste time I understand and I can figure out a way to merge this.

**Comment by william57m** [comment]
Hi @ealves-pt I'll take a look this week if I can do it quickly.

**Comment by ealves-pt** [comment]
@william57m yeah you are right, I have looked into your code and there a couple of things that have changed. Any help is welcome :+1: 

Thanks

**Comment by grevory** [comment]
#351 covers this. Thanks guys!

**Pull request closed without merging**
