### PR TITLE
Add option to set the secure flag on a fallback cookie

### PR DESCRIPTION
**Pull request by barefootdeveloper**
I wanted to have the fallback cookie be set in secure mode. This is useful for those that want to store information in the local storage that they wouldn't want getting sent over an encrypted channel.

### CODE REVIEW

**Comment by quozd** [comment]
+1

**Comment by ruipenso** [comment]
Any plans to merge this?

**Comment by michaellieberherrr** [comment]
+1

**Comment by azhub** [comment]
+1

**Comment by barefootdeveloper** [comment]
Looks like PR#283 includes similar functionality, i'm going to close this.

**Pull request closed without merging**
