### PR TITLE
Added features, "Changed" broadcast, disabling defaultToCookies, added closure

### PR DESCRIPTION
**Pull request by Snede**
This pull request contains three feature changes.

1. First of all, the code has been wrapped in a closure to avoid cluttering the global variable space.

2. The lib will default to cookies if localstorage is enabled, this behavior can now be disabled.

3. If other tabs/windows make changes in the localstorage on keys that is owned by this service, it will now be broadcasted.

### CODE REVIEW

**Comment by grevory** [comment]
This PR looks outstanding. I have one request before I accept. You've added new features and decreased test coverage. Would you might adding some tests to cover defaulting to cookies?

**Comment by Snede** [comment]
Thank you :)

Yes ofcourse, I will do it as soon as I can find the time. I hope I can get to it this week.

**Comment by Snede** [comment]
Hmm, I'm having difficulties setting up the test environment. I cannot get grunt to create the coverage files. They just stay empty.

Although I can get it to run the tests.

I'm using Windows 10, and not familiar with npm, bower, grunt etc.

**Comment by Snede** [comment]
There we go :)

**Comment by Snede** [comment]
@grevory Does this fulfill your test requirements?

**Comment by grevory** [comment]
Sorry have been travelling with work and taking care of an new infant at home. Will review soon. Thanks!

**Comment by grevory** [comment]
Thanks!

**Pull request merged**
