### PR TITLE
CommonJS Support

### PR DESCRIPTION
**Pull request by seanhealy**
Adding CommonJS support. Tried to follow the pattern than the other angular core modules are following. If you have feedback please let me know. :)

### CODE REVIEW

**Comment by seanhealy** [comment]
Had a couple odd issues. Will re-open once they are resolved.

**Comment by a8m** [comment]
@seanhealy can you squash these commits? thanks

**Comment by jonespen** [comment]
+1

**Comment by seanhealy** [comment]
@a8m Finally got back to this. Hopefully that's what you're looking for.

**Comment by ctaepper** [comment]
+1

**Comment by SamMorrowDrums** [comment]
Yeah, this looks good - how all Angular packages work on NPM now.

**Comment by ealves-pt** [comment]
This was closed by PR #279 where UMD module definition was added.

**Pull request closed without merging**
